### PR TITLE
Install Auth0 dependencies via NPM/Yarn

### PR DESCRIPTION
**Pull request by XaserAcheron**
The Ember ecosystem is rapidly shying away from Bower (including [Ember itself](http://emberjs.com/blog/2017/01/23/ember-2-11-released.html) from v2.11.0 onward), and Yarn is creeping up as the package manager of the future. Figure it's about time to make the leap.

This PR adds `auth0.js`, `auth0-lock`, and `auth0-lock-passwordless` as `package.json` dependencies and removes them from `bower.json`, and includes all the Broccoli magic needed to make it work.

Pros to this approach:
- No need for consuming apps to include the three Auth0 libraries in their `bower.json` for this addon to work; it Just Works(tm), installing the necessary dependencies automagically.
- Consuming apps for Ember v2.11.0+ are not blocked from ousting Bower entirely (e.g. my own project which spurred me to make this PR; it's all `yarn` now).
  - The same applies for `ember-simple-auth-auth0` itself. ;)
- No more Auth0Lock or Auth0LockPasswordless globals (though Auth0's global still exists since that's how it wants to work).
- No need for vendor shims to string the libraries together; the project is a bit cleaner now.
- Did I mention Yarn yet? :P

Cons:
- ...

[I'm being somewhat cheeky with this last one, but in-my-possibly-biased-opinion, it's a strict upgrade. ;]

All tests are passing, and I'm using this fork in my own project with no issues, so hopefully everything's all kosher. As a heads-up, I did clean up some commented-out code in `index.js` toward the end; if that's undesired, I can revert that piece. Just figured I'd include that bit of housekeeping while I was at it.

Hope this helps, and thanks @seawatts for keeping this addon up-to-date with all the latest Lock goodness!

### CODE REVIEW

**Comment by XaserAcheron** [comment]
Hmm, looks like Travis has made the Cons list a bit less empty: `auth0-lock` expects a really recent version of Node (>=6.9.1), so that's something to keep in mind. I suppose this should be a `v4.0.0`+ thing at the very least.

**Comment by selbyk** [comment]
👍

**Comment by selbyk** [comment]
I'm attempting to use the released 3 version of this addon in an Ember app that has abandoned bower and npm.  What's the easiest why to work around all the `Error: ENOENT: no such file or directory, open '/Users/selby/projects/.../tmp/source_map_concat-input_base_path-potXE7WD.tmp/bower_components/auth0-lock-passwordless/build/lock-passwordless.js'` errors?

**Comment by XaserAcheron** [comment]
@selbyk That's one of the things this PR addresses. The release version of this addon relies on `auth0.js`, `auth0-lock`, and `auth0-lock-passwordless` to be installed in your app via Bower or else you get those errors. It's basicllay looking for a file that doesn't exist.

If you're feeling adventurous, you can point `yarn` at my branch by changing the `ember-simple-auth-auth0` (dev)dependency in `package.json` to the following:
```javascript
    "ember-simple-auth-auth0": "https://github.com/XaserAcheron/ember-simple-auth-auth0.git#bower-nix-v1",
```

`bower-nix-v1` is a new branch I created with all the changes in it, just I need to update this PR for change requests or bugfixes or whatnot.

Hope this helps!

**Comment by selbyk** [comment]
@XaserAcheron Thanks for the quick response.  That's what I was afraid you were going to say!

@seawatts What are your thoughts on the immediate future of this addon and plans to merge in this PR?

**Comment by seawatts** [comment]
This PR looks pretty good. I would have gone a different route on importing the dependencies but overall looks like the right idea. 

I would have rather used `https://github.com/kellyselden/ember-cli-node-modules-to-vendor`

**Comment by seawatts** [comment]
Can you resolve these conflicts and then we can merge

**Comment by XaserAcheron** [comment]
I'm in a huge project crunch so I won't be able to take a look at this for a week or so, but I'm having some second thoughts on using `broccoli-webpack` anyway -- or at least one potential issue to investigate. Out of curiosity, does `ember-cli-node-modules-to-vendor` handle CommonJS modules? That's the reason I had to bring in `broccoli-webpack`, since Auth0 distributes their npm versions that way.

Sorry for the bad timing. I'll get back on this when I can.

**Comment by XaserAcheron** [comment]
Wow. That was a long "week or so". ;)

Reviewed this, made a small update, and merged the latest changes from `develop`. I think I'm happy with this now.

Any last thoughts, @seawatts, or is this good to go?


[Quick P.S.: Travis is balking at `bower.json` not existing anymore, but I've elected not to change that just yet since I'm not sure how that's supposed to work with `ember-try` and older Ember releases -- bower still needs to be installed+run for the 2.4 and 2.8 LTS tests.]

**Comment by seawatts** [comment]
Hmm yeah that is an interesting situation with bower. I would probably just remove it from the build steps. I can't merge this until its passing

**Comment by XaserAcheron** [comment]
Any advice? I don't use `ember-try` personally so I'd be throwing stuff at it blindly until it works.

**Comment by XaserAcheron** [comment]
Never mind. Sometimes the best solutions are the simplest -- I just threw in a `bower.json` with zero dependencies and all is well. ;)

**Comment by eturino** [comment]
@seawatts @XaserAcheron what's the status of this? we're working on removing bower from our app and I think ember-simple-auth-auth0 is our last impediment :)

**Comment by XaserAcheron** [comment]
Up to @seawatts now -- all the ducks seem to be in a row from my end.

🐦 :dagger:

**Comment by seawatts** [comment]
This looks great! I'll merge and push a new release!

**Comment by seawatts** [comment]
Oops

**Comment by XaserAcheron** [comment]
Thanks for the merge! 👍

**Pull request merged**
