### PR TITLE
update dependencies

### PR DESCRIPTION
**Pull request by miguelcobain**
Initially did this PR to update ember-simple-auth dependency.
This was forcing apps to use a previous version which introduce some deprecations on the consuming app.

Also updated the project's dependencies and got rid of some deprecations:
- stop using Ember.merge
- stop using Ember.Logger
- stop using `new` with `EmberObject` subclasses

Also bumped other dependencies.

### CODE REVIEW

**Comment by XaserAcheron** [comment]
Welp! We double-worked this, I think -- see #150.

Looking at mine, though, the actual dependencies in `package.json` (rather annoyingly) haven't changed -- yarn just updated `yarn.lock` and marked it 'done'. Might be a good idea to merge this anyway so it's nice n' explicit.

**Comment by miguelcobain** [comment]
I think both PRs complement each other well.

**Comment by miguelcobain** [comment]
@XaserAcheron any news on this?

**Comment by XaserAcheron** [comment]
Sorry, I haven't had the time. I can't hit the "merge" button on this because Snyk is complaining at something, and I'm not sure what the correct path forward is just yet.

**Comment by XaserAcheron** [comment]
Whew, all good now -- sorry this sat in limbo for so long, @miguelcobain, and thanks so much for the help!

**Pull request merged**
