### PR TITLE
Fastboot 1.0

### PR DESCRIPTION
**Pull request by FilmKnurd**
Addresses #50 

Probably more to do... but this fixes the document reference error.

### CODE REVIEW

**Comment by FilmKnurd** [comment]
The libraries exist is vendor... but can't seem to be imported
```
ember.debug.js:19818 Error: Could not find module `vendor/auth0` imported from `ember-simple-auth-auth0/services/auth0`
```

**Comment by seawatts** [comment]
I would rather just use https://github.com/kellyselden/ember-cli-node-modules-to-vendor

**Comment by FilmKnurd** [comment]
Oh nice, and then can remove the bower dependencies.

**Comment by XaserAcheron** [comment]
#145 ended up handling this, I think.

**Pull request closed without merging**
