### PR TITLE
use ember-auto-import

### LINKED ISSUE #124: Replace broccoli-webpack with better cjs import method
Split from #122/#123.

There seem to be better alternatives to than `broccoli-webpack` for importing CJS modules nowadays, so let's upgrade.

Couple of candidates:
- [ember-cli-cjs-transform](https://github.com/rwjblue/ember-cli-cjs-transform)
- [ember-auto-import](https://github.com/ef4/ember-auto-import)

The latter would be most fantastic, so long as it works in addons without mucking with upstream apps.

Thanks @miguelcobain for bringing this up! Tagging you again since we both seem to be pretty interested in this.

### PR DESCRIPTION
**Pull request by miguelcobain**
Seems that ember-auto-import allows us to use it in addons!
This is great news.

Also removed `bower.json` and `.bowerrc` files and removed some unrelated npm dependencies that don't seem to be used/needed.

The last remaining question is about the webpack plugin about `process.ENV.NODE_ENV` (in these lines https://github.com/auth0-community/ember-simple-auth-auth0/blob/develop/index.js#L27-L29).
In [your commit](https://github.com/auth0-community/ember-simple-auth-auth0/commit/df35dad9ac9ed737c4a6a59b5c7454d1c4c90cb1) you say that's for using the production react on production builds.
Is that still needed? ember-auto-import allows us to configure webpack, so we can keep doing it.
Just let me know and I'll add it.

Closes #124

### CODE REVIEW

**Comment by XaserAcheron** [comment]
This is awesome! 👍 

It's definitely worth putting in the `process.ENV.NODE_ENV` stuff back in. The gist is that React throws a console warning if a minified development version is loaded in the browser (performance concerns and whatnot). It's benign, but everyone who uses this addon would then have to put up with the warning, which isn't great.

Shouldn't be too difficult to add, fortunately. I'm not quite in a position to try this out just yet (though I'll try and make time ASAP to get this tested+merged), but the following `index.js` should do the trick:
```js
'use strict';

const EmberAddon = require('ember-cli/lib/broccoli/ember-addon');
const wp = require('webpack');

module.exports = {
  name: 'ember-simple-auth-auth0',
  options: {
    autoImport: {
      webpack: {
        plugins: [
          new wp.DefinePlugin({
            'process.env.NODE_ENV': JSON.stringify(EmberAddon.env())
          })
        ]
      }
    }
  }
};
```

Otherwise, this is super-fantastic!

Sorry for being so absent these days. Seems like you're doing more maintenance work than me at this point. :P

**Comment by miguelcobain** [comment]
@XaserAcheron added back the webpack plugin.

I used what auth0-lock recommends in their example files: https://github.com/auth0/lock/blob/master/examples/bundling/webpack/webpack.config.js

**Comment by miguelcobain** [comment]
I actually went back to using `'process.env.NODE_ENV': JSON.stringify(EmberAddon.env())`, since that's what webpack docs recommend:

> When defining values for process prefer 'process.env.NODE_ENV': JSON.stringify('production') over process: { env: { NODE_ENV: JSON.stringify('production') } }. Using the latter will overwrite the process object which can break compatibility with some modules that expect other values on the process object to be defined.

**Comment by miguelcobain** [comment]
I updated some sinon related dependencies because of a ember-cli-babel 5.X deprecation.
We're left with one, though: ember-cli-changelog.
Right now the project is using a @seawatts fork. I see some commits there that aren't on the main repo.
We should either: update that fork with upstream changes or use upstream entirely.

Other packages that I think are candidates for removal:
- jsonwebtoken (didn't see any usage of it)
- ember-cli-commands (seems irrelevant now that the standard is the official ember-cli-update project)

**Comment by miguelcobain** [comment]
Note: nevermind the Broccoli deprecations. Those will be fixed once ember-simple-auth releases a new version (it is fixed on master). See https://github.com/simplabs/ember-simple-auth/issues/1615

**Comment by XaserAcheron** [comment]
`jsonwebtoken` indeed seems a bit redundant -- it's a dependency of `express-jwt` (which is used for tests) but it should just get pulled in.

`ember-cli-commands` pre-dates my involvement and seems like a convenience library mostly; I haven't used it myself, so it can probably go.

For `ember-cli-changelog`, the @seawatts branch has what looks like a bugfix (i think?) and a 2nd commit that changes the commit format to use author handles (e.g. `@XaserAcheron`) instead of full names (`Xaser Acheron`)... which is weird because the changelog in this project uses full names. o_O

I think some of these are a bit beyond the scope of this PR, though they're definitely worth addressing.

**Comment by miguelcobain** [comment]
> I think some of these are a bit beyond the scope of this PR, though they're definitely worth addressing.

Agree. They're just `devDependencies`, so they don't represent additional weight for the end users.

This should be ready to merge then. Let me know if you find anything wrong with this.

**Comment by miguelcobain** [comment]
@xaseracheron you're welcome. Thanks for maintaining this addon!

I believe that that core team os considering including something like ember-auto-import by default. So yes, the future is bright. 👍

**Pull request merged**
