### PR TITLE
Add native support for Silent Authentication

### PR DESCRIPTION
**Pull request by XaserAcheron**
Adds Silent Authentication support. In addition to adding an `auth0-silent-auth` authenticator, this also adds a few flags to enable automatic token renewal in various ways.

This is all opt-in via `environment.js`, so here's an example configuration hash with all the various options enabled:
```js
// config/environment.js
module.exports = function(environment) {
  let ENV = {
    'ember-simple-auth': {
      // ...

      auth0: {
        // ...

        silentAuth: {

          // automatically renew token every 30 minutes:
          renewSeconds: 1800,

          // automatically renew token when trying to restore an expired session (on app load):
          onSessionRestore: true,

          // automatically renew token when token expiration time is hit (during app use):
          onSessionExpire: true,

          // options to pass to checkSession when doing automatic silent auth.
          // The redirectUri parameter is automatically set to window.location.origin
          // if not specified.
          options: {
            responseType: 'token id_token',
            scope: 'openid profile email',
            timeout: 5000
          }
        }
      }
    }
  };

  return ENV;
};
```

I'm not super-attached to the `renewSeconds` name, so feel free to suggest alternatives. Or any in general -- naming things is hard!

### CODE REVIEW

**Comment by EUGinsane** [comment]
@XaserAcheron sry for disturbing, I tried to make the change as described in your comment but it seems not to work atm in my application. I set the JWT token to be expired in 30s in the dashboard to make it easier to test, but it keeps logout after the token is expired. Here is the configuration in my `environment.js`:

```
'ember-simple-auth': {
      authenticationRoute: 'login',
      auth0: {
        clientID: AUTH_CONFIG.clientId,
        domain: AUTH_CONFIG.domain,
        logoutReturnToURL: '/logout',
        enableImpersonation: false,
        silentAuth: {
          renewSeconds: 30,
          onSessionRestore: true,
          onSessionExpire: true,
          options: {
            responseType: AUTH_CONFIG.responseType,
            scope: AUTH_CONFIG.scope,
            timeout: 5000,
            redirectUrl: AUTH_CONFIG.redirectUrl,
            redirect: AUTH_CONFIG.redirect,
          },
        },
      },
    },
```

any pro tips ? thanks

**Comment by XaserAcheron** [comment]
Which version of the addon are you using? The Silent Auth feature is currently only available in the `4.2.0-alpha` releases, so that might be it.

**Comment by EUGinsane** [comment]
The current version that I am using is `4.2.0-beta.4`, I will try to change it into `4.2.0-alpha`. Thanks for the response @XaserAcheron

**Comment by XaserAcheron** [comment]
Sorry, typo -- I should've said `beta` -- that's the correct version.

I'm not sure what else to suggest offhand -- sorry.

**Comment by EUGinsane** [comment]
I made the changes in `environment.js` as described in your first comment @XaserAcheron but it did not run. Please consider to check on this issue #160 for more detail.

**Pull request merged**
